[project]
name = "hugr-qir"
dynamic = ["version"]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "guppylang>=0.14.0",
    "quantinuum-qircheck",
]

[dependency-groups]
dev = [
    "maturin>=1.1,<2.0",
    "pip>=24.3.1",
    "pytest>=8.3.4",
    "ruff>=0.9.0"
]

[build-system]
requires = ["maturin>=1.1,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "hugr_qir._hugr_qir"
python-source = "python"
python-packages = ["hugr_qir"]
bindings = "pyo3"

[tool.uv.sources]
quantinuum-qircheck = { git = "https://github.com/CQCL/quantinuum-qircheck.git" }
